create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clock]
set_property PACKAGE_PIN K17 [get_ports clock]
set_property PACKAGE_PIN Y16 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports io_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports io_txd]
set_property PACKAGE_PIN H15 [get_ports io_txd]
set_property PACKAGE_PIN J15 [get_ports io_rxd]