// Generated by CIRCT firtool-1.62.0
module ALU(	// src/main/scala/ALU.scala:4:7
  input  [3:0] io_b,	// src/main/scala/ALU.scala:8:14
               io_op,	// src/main/scala/ALU.scala:8:14
  output [3:0] io_out	// src/main/scala/ALU.scala:8:14
);

  wire [18:0] _io_out_T_10 = 19'h5 << io_b;	// src/main/scala/ALU.scala:24:25
  assign io_out =
    io_op == 4'h0
      ? io_b + 4'h5
      : (io_op[0] ? 4'h5 - io_b : 4'h0) | (io_op[1] ? io_b & 4'h5 : 4'h0)
        | (io_op[2] ? io_b ^ 4'h5 : 4'h0) | (io_op[3] ? _io_out_T_10[3:0] : 4'h0);	// src/main/scala/ALU.scala:4:7, :8:14, :17:{15,20}, :18:{12,20}, :20:12, :21:{12,25}, :22:{12,25}, :23:{12,25}, :24:{12,25}, src/main/scala/chisel3/util/Mux.scala:30:73
endmodule

module Top(	// src/main/scala/Top.scala:3:7
  input        clock,	// src/main/scala/Top.scala:3:7
               reset,	// src/main/scala/Top.scala:3:7
  input  [3:0] io_in,	// src/main/scala/Top.scala:10:14
               io_op,	// src/main/scala/Top.scala:10:14
  output [3:0] io_out	// src/main/scala/Top.scala:10:14
);

  ALU alu (	// src/main/scala/Top.scala:16:19
    .io_b   (io_in),
    .io_op  (io_op),
    .io_out (io_out)
  );
endmodule

